# Generated by Django 4.1.4 on 2024-08-17 14:56
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("features", models.TextField(blank=True, null=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, null=True),
                ),
                ("technologies", models.CharField(max_length=300)),
                ("demo_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True)),
                (
                    "gradient",
                    models.TextField(
                        choices=[
                            ("from-cyan-300 to-blue-400", "Blue"),
                            ("from-white to-blue-400", "Light Blue"),
                            ("from-red-300 to-red-600", "Red"),
                            ("from-white to-red-300", "Light Red"),
                            ("from-pink-400 to-purple-400", "Purple"),
                            (
                                "from-white to-purple-400",
                                "Light Purple",
                            ),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "gradient",
                    models.TextField(
                        choices=[
                            ("from-cyan-300 to-blue-400", "Blue"),
                            ("from-white to-blue-400", "Light Blue"),
                            ("from-red-300 to-red-600", "Red"),
                            ("from-white to-red-300", "Light Red"),
                            ("from-pink-400 to-purple-400", "Purple"),
                            (
                                "from-white to-purple-400",
                                "Light Purple",
                            ),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "rate",
                    models.IntegerField(
                        blank=0,
                        default=0,
                        verbose_name="Rate (out of 100)",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, default="", max_length=200
                    ),
                ),
                (
                    "gradient",
                    models.TextField(
                        choices=[
                            ("from-cyan-300 to-blue-400", "Blue"),
                            ("from-white to-blue-400", "Light Blue"),
                            ("from-red-300 to-red-600", "Red"),
                            ("from-white to-red-300", "Light Red"),
                            ("from-pink-400 to-purple-400", "Purple"),
                            (
                                "from-white to-purple-400",
                                "Light Purple",
                            ),
                        ]
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="portfolio.skillcategory",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="portfolio.skilltype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=30
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="skills_about",
                        to="portfolio.skill",
                    ),
                ),
            ],
        ),
    ]
