# Generated by Django 4.1.4 on 2024-08-21 08:12
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [("portfolio", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, unique=True),
                ),
                ("description", models.CharField(max_length=300)),
                ("features", models.TextField(blank=True, null=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, null=True),
                ),
                ("technologies", models.CharField(max_length=300)),
                ("demo_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="AboutMe", new_name="AboutMeModel"
        ),
        migrations.RenameModel(old_name="Skill", new_name="SkillModel"),
        migrations.DeleteModel(name="Project"),
    ]
