# Generated by Django 4.1.4 on 2024-08-17 10:33
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "sno",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("meta", models.CharField(max_length=300)),
                ("content", models.TextField()),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        default="uncategorized", max_length=255
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
