# Generated by Django 5.1 on 2024-08-26 11:27
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "blog",
            "0002_delete_category_alter_blogmodel_options_and_more",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=40, null=True
            ),
        )
    ]
